# Importing required packages

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [3]:
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout, Activation, Flatten

# Importing dataset

In [4]:
dataset_path = "data/preprocessed.csv"

In [5]:
dataset = pd.read_csv(dataset_path, index_col = False)

In [6]:
dataset.columns

Index(['Staff', 'Floor Space', 'Window', 'Car park', 'Demographic score',
       '40min population', '30 min population', '20 min population',
       '10 min population', 'Store age', 'Clearance space',
       'Competition number', 'Competition score', 'location0', 'location1',
       'location2', 'performance'],
      dtype='object')

In [7]:
data = dataset.iloc[:, :].values

# Extracting dependant and independant variables

In [8]:
y = data[:, -1]

In [9]:
X = data[:, :-1]

In [10]:
y.shape

(134,)

In [11]:
X.shape

(134, 16)

# Performing train test split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
optimizer = SGD(learning_rate=0.01)

In [14]:
model = Sequential()

model.add(Dense(16, input_shape=(X_train.shape[1],), activation="tanh"))
model.add(Dropout(0.1))

model.add(Dense(32, input_shape=(X_train.shape[1],), activation="tanh"))
model.add(Dropout(0.2))

model.add(Dense(64, activation="relu"))
model.add(Dropout(0.3))

model.add(Dense(128, activation="relu"))
model.add(Dropout(0.5))

model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer = optimizer,loss="binary_crossentropy",metrics=["accuracy"])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                272       
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense_3 (Dense)             (None, 128)               8

In [18]:
history = model.fit(X_train,
                    y_test,
                    epochs = 200,
                    batch_size = 64,
                    validation_split=0.1)

Epoch 1/200
2/2 [==============================] - 0s 62ms/step - loss: 0.6891 - accuracy: 0.5750 - val_loss: 0.7072 - val_accuracy: 0.3571
Epoch 2/200
2/2 [==============================] - 0s 30ms/step - loss: 0.6885 - accuracy: 0.5417 - val_loss: 0.7075 - val_accuracy: 0.2857
Epoch 3/200
2/2 [==============================] - 0s 36ms/step - loss: 0.6978 - accuracy: 0.5333 - val_loss: 0.7078 - val_accuracy: 0.2857
Epoch 4/200
2/2 [==============================] - 0s 35ms/step - loss: 0.7067 - accuracy: 0.5167 - val_loss: 0.7082 - val_accuracy: 0.2857
Epoch 5/200
2/2 [==============================] - 0s 32ms/step - loss: 0.7028 - accuracy: 0.5333 - val_loss: 0.7085 - val_accuracy: 0.3571
Epoch 6/200
2/2 [==============================] - 0s 35ms/step - loss: 0.6777 - accuracy: 0.5833 - val_loss: 0.7086 - val_accuracy: 0.3571
Epoch 7/200
2/2 [==============================] - 0s 32ms/step - loss: 0.7002 - accuracy: 0.5250 - val_loss: 0.7089 - val_accuracy: 0.4286
Epoch 8/200
2/2 [===

2/2 [==============================] - 0s 28ms/step - loss: 0.6806 - accuracy: 0.5167 - val_loss: 0.7201 - val_accuracy: 0.4286
Epoch 60/200
2/2 [==============================] - 0s 29ms/step - loss: 0.6809 - accuracy: 0.4917 - val_loss: 0.7204 - val_accuracy: 0.4286
Epoch 61/200
2/2 [==============================] - 0s 29ms/step - loss: 0.6750 - accuracy: 0.5917 - val_loss: 0.7205 - val_accuracy: 0.4286
Epoch 62/200
2/2 [==============================] - 0s 29ms/step - loss: 0.6567 - accuracy: 0.6417 - val_loss: 0.7207 - val_accuracy: 0.4286
Epoch 63/200
2/2 [==============================] - 0s 28ms/step - loss: 0.6878 - accuracy: 0.5333 - val_loss: 0.7206 - val_accuracy: 0.4286
Epoch 64/200
2/2 [==============================] - 0s 29ms/step - loss: 0.6643 - accuracy: 0.6000 - val_loss: 0.7208 - val_accuracy: 0.4286
Epoch 65/200
2/2 [==============================] - 0s 31ms/step - loss: 0.6879 - accuracy: 0.5417 - val_loss: 0.7209 - val_accuracy: 0.4286
Epoch 66/200
2/2 [========

2/2 [==============================] - 0s 36ms/step - loss: 0.6798 - accuracy: 0.5833 - val_loss: 0.7227 - val_accuracy: 0.4286
Epoch 118/200
2/2 [==============================] - 0s 33ms/step - loss: 0.6939 - accuracy: 0.5000 - val_loss: 0.7228 - val_accuracy: 0.4286
Epoch 119/200
2/2 [==============================] - 0s 35ms/step - loss: 0.6722 - accuracy: 0.5833 - val_loss: 0.7226 - val_accuracy: 0.4286
Epoch 120/200
2/2 [==============================] - 0s 34ms/step - loss: 0.7093 - accuracy: 0.5083 - val_loss: 0.7225 - val_accuracy: 0.4286
Epoch 121/200
2/2 [==============================] - 0s 33ms/step - loss: 0.6676 - accuracy: 0.5833 - val_loss: 0.7227 - val_accuracy: 0.4286
Epoch 122/200
2/2 [==============================] - 0s 34ms/step - loss: 0.6894 - accuracy: 0.5333 - val_loss: 0.7227 - val_accuracy: 0.4286
Epoch 123/200
2/2 [==============================] - 0s 35ms/step - loss: 0.6835 - accuracy: 0.5167 - val_loss: 0.7229 - val_accuracy: 0.4286
Epoch 124/200
2/2 [=

Epoch 175/200
2/2 [==============================] - 0s 30ms/step - loss: 0.6637 - accuracy: 0.6417 - val_loss: 0.7226 - val_accuracy: 0.4286
Epoch 176/200
2/2 [==============================] - 0s 28ms/step - loss: 0.6891 - accuracy: 0.5333 - val_loss: 0.7225 - val_accuracy: 0.4286
Epoch 177/200
2/2 [==============================] - 0s 31ms/step - loss: 0.6902 - accuracy: 0.5083 - val_loss: 0.7225 - val_accuracy: 0.4286
Epoch 178/200
2/2 [==============================] - 0s 31ms/step - loss: 0.6714 - accuracy: 0.5583 - val_loss: 0.7224 - val_accuracy: 0.4286
Epoch 179/200
2/2 [==============================] - 0s 31ms/step - loss: 0.6532 - accuracy: 0.6500 - val_loss: 0.7222 - val_accuracy: 0.4286
Epoch 180/200
2/2 [==============================] - 0s 30ms/step - loss: 0.6680 - accuracy: 0.5667 - val_loss: 0.7223 - val_accuracy: 0.4286
Epoch 181/200
2/2 [==============================] - 0s 31ms/step - loss: 0.6584 - accuracy: 0.6000 - val_loss: 0.7225 - val_accuracy: 0.4286
Epoch 

In [19]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 28ms/step - loss: 0.6629 - accuracy: 0.7037


[0.662899374961853, 0.7037037014961243]

In [20]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 87ms/step


In [28]:
y_test

array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 0., 0.])

In [29]:
predicted = []
for i in y_pred:
    if i >=0.5:
        predicted.append(1.)
    else:
        predicted.append(0.)

array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
cm = confusion_matrix(y_test, np.array(predicted))
cm

array([[ 2,  8],
       [ 0, 17]], dtype=int64)